hdfs.uri=hdfs://localhost:8020
hdfs.user=hadoop
hdfs.raw.base=/data/logs
hdfs.clean.base=/data/clean
local.raw.dir=../crawler/data/export
local.raw.scenic=scenic_raw.csv
local.raw.show=show_raw.csv
local.raw.ktv=ktv_raw.csv
local.raw.movie=movie_raw.csv
local.raw.sport=sport_raw.csv
mysql.host=localhost
mysql.port=3306
mysql.database=wenyu_result
mysql.username=root
mysql.password=root
hive.bin=hive
sqoop.bin=sqoop
batch.date=2026-03-23
