hdfs.uri=hdfs://localhost:8020
hdfs.user=hadoop
hdfs.raw.base=/data/logs
hdfs.clean.base=/data/clean
local.raw.dir=../crawler/data/export
local.raw.rental=rental_raw.csv
mysql.host=localhost
mysql.port=3306
mysql.database=rental_result
mysql.username=root
mysql.password=root
hive.bin=hive
sqoop.bin=sqoop
batch.date=2026-03-23
